# Usar a imagem base do MySQL
FROM mysql:8

# Definir variáveis de ambiente para o MySQL
ENV MYSQL_DATABASE=atividade_docker
ENV MYSQL_USER=root
ENV MYSQL_PASSWORD=rootpassword
ENV MYSQL_ROOT_PASSWORD=rootpassword

# Expor a porta 3306
EXPOSE 3306
